### ISSUE TITLE
node.removeChildren 

### ISSUE THREAD

**Issue by sophister** [mbraak/jqTree#446]
how can I remove **all children** of a `node`, using `tree('updateNode', node, { id : 'xxx', children : [] })` fails because `children` is empty.

I find `node.removeChildren()` and `node.loadFromData(data.children)` in `JqTreeWidget.prototype.updateNode`, but these methods are NOT in document.

can I use these methods directly?

**Comment by mbraak** [comment]
You can use the [loadData](https://mbraak.github.io/jqTree/#functions-loaddata) function for this:

```js
var node = $tree.tree('getNodeByName', 'Coelurosaurians');

// Load empty tree into this node; this removes all children
$tree.tree('loadData', [], node);
```

You cannot use the `node.removeChildren` and `node.loadFromData` functions because these will only operate on the underlying data and will not update the tree.

I will have a look at the `updateNode` function, because it should be possible to remove children that way.

**Comment by sophister** [comment]
@mbraak  OK

**Comment by mbraak** [comment]
The `updateNode` function is now fixed. Also see #448.
