### ISSUE TITLE
Scroll top on addToSelection

### ISSUE THREAD

**Issue by Costegillio** [mbraak/jqTree#520]
Greetings!

I use plugin in multiple-selection mode just like in example. I have custom function which recursive select all parents:
`

		            function selectParent(node) {
		            	
		            	if (typeof node !== 'undefined') {
		            		
		            		var parent = node.parent;

			            	if (typeof parent !== null) {
				    		 	var parentNode = el.tree('getNodeById', parent.id);
				    		 	el.tree('addToSelection', parentNode);
				    		 	selectParent(parentNode);
			            	}
		            	
		            	}
		            	
		            }`

It works fine but on 'addToSelection' step window scrolled top what is really annoying. How to prevent window from scroll on it?

Plugin is awesome, thanks!

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
The problem here is that `addToSelection` sets the focus to the selected node. This causes the scrolling.

I added  the `mustSetFocus` parameter to the `addToSelection` function. If you set it to false, then the node will not be selected:

```
el.tree('addToSelection', parentNode, false);
```

The change is in the `dev` branch, not yet in the npm release. Please let me know if the solution works.

**Comment by Costegillio** [comment]
Works like a charm, though.

Thanks a lot!
