### ISSUE TITLE
Middle mouse button click event

### ISSUE THREAD

**Issue by Clans** [mbraak/jqTree#628]
Hello,

How can I handle the middle mouse button click event?
Thanks!

**Comment by mbraak** [comment]
I will have a look to see if that is possible.

**Comment by mbraak** [comment]
Jqtree doesn't have an event for a middle mouse button click. But it is possible to attach an event handler:

```js
const $tree = $("#tree1");

$tree.tree({
    autoOpen: 0,
    data: ExampleData.exampleData,
});

$tree.on("auxclick", (e) => {
    if (e.button === 1) {
        const node = $tree.tree("getNodeByHtmlElement", e.target);

        if (node) {
            console.log(`click on ${node.name}`);
        }
    }
});
```

* Use [getNodeByHtmlElement](https://mbraak.github.io/jqTree/#functions-getnodebyhtmlelement) to find the node for the html element.
* This event also fires for the right mouse button. `event.button` is 1 for the middle mouse button.
* This might not work in some browser (Internet Explorer, Safari). In that case use the `mousedown` or `mouseup` event (instead of `auxclick`).
  * Also see https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event

**Comment by Clans** [comment]
Works fine, thanks!
