### ISSUE TITLE
Exports is not defined

### ISSUE THREAD

**Issue by duaneelkins** [mbraak/jqTree#638]
Hi .... I'm trying to implement jqTree into a MVC application.

I've included tree.jquery.js, and jqTree.css using my BundlesConfig ..... I can see them load through the browser console.

I've created a div and tried to populated it as such:

var data = [
            {
                name: 'node1', id: 1,
                children: [
                    { name: 'child1', id: 2 },
                    { name: 'child2', id: 3 }
                ]
            },
            {
                name: 'node2', id: 4,
                children: [
                    { name: 'child3', id: 5 }
                ]
            }
        ];
     
        $('#test').tree({
            data: data,
            dragAndDrop: true,
            autoOpen: 0
        });

However, I'm getting the following in the console:

"Uncaught ReferenceError: exports is not defined" from tree.jquery.js:26:1
"Uncaught TypeError: $(...).tree is not a function" from myPage

Any help would be appreciated ......

**Comment by mbraak** [comment]
I'll have a look.

**Comment by duaneelkins** [comment]
Awesome .... thank you.

**Comment by mbraak** [comment]
Some issues that I can think of:

Perhaps jquery is not included? Jqtree depends on the jquery library.

Are you using the jqtree-rails gem? It's better not to use that because it includes a very old version of jqtree (from 2013). The latest version is version 1.5.2. from 2020. (I'm asking this because you mentioned the BundlesConfig).

Alternatives for the jqtree-rails gem are [npm](https://www.npmjs.com/package/jqtree), [bower](https://bower.io/) or you can copy the files from github: https://mbraak.github.io/jqTree/tree.jquery.js and https://mbraak.github.io/jqTree/jqtree.css

**Comment by duaneelkins** [comment]
Cool .... maybe it was a version issue.  
Seems to be working now ..... thank you.

**Comment by duaneelkins** [comment]
I have a follow up question ..... is there anyway to add the dnd features to an existing unordered list?

Let's say I have:

<ul>
   <li>1</li>
   <li>2</li>
</ul>

already loaded in the dom .... can I somehow apply jqTree to it to make it draggable/droppable?

**Comment by mbraak** [comment]
No, that's not possible using jqtree.

There are other libraries that supports this: https://sortablejs.github.io/Sortable/ and https://bevacqua.github.io/dragula/ Those libraries have excellent dnd features but are less oriented at tree structures.
